### ISSUE TITLE
Issue with prune_network() function in Brahmaputra tutorial

### ISSUE THREAD

**Issue by huck-rees** [VeinsOfTheEarth/RivGraph#100]
Hello, I am very excited to be working with this toolset! However, when I try and complete the braided river tutorial, I encounter the following error when I get to the brahma.prune_network() function in step 4. Keep in mind I am using the mask provided with the tutorial and everything worked properly prior to this step. Here is the full error message: "---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[52], line 1
----> 1 brahma.prune_network()
      3 # We see that 'inlets' and 'outlets' have been added to the nodes dictionary:
      4 print(brahma.nodes.keys())

File ~\miniconda3\Lib\site-packages\rivgraph-0.5.0-py3.11.egg\rivgraph\classes.py:787, in river.prune_network(self)
    784 if hasattr(self, 'Iskel') is False:
    785     self.skeletonize()
--> 787 self.links, self.nodes = ru.prune_river(self.links, self.nodes, self.exit_sides, self.Iskel, self.gdobj)

File ~\miniconda3\Lib\site-packages\rivgraph-0.5.0-py3.11.egg\rivgraph\rivers\river_utils.py:35, in prune_river(links, nodes, exit_sides, Iskel, gdobj)
     31 nodes = find_inlet_outlet_nodes(links, nodes, exit_sides, Iskel)
     33 # Remove spurs from network (this includes valid inlets and outlets unless
     34 # specified not to remove)
---> 35 links, nodes = lnu.remove_all_spurs(links, nodes,
     36                                     dontremove=list(nodes['inlets'] +
     37                                                     nodes['outlets']))
     39 # # Add artificial nodes where necessary
     40 # links, nodes = lnu.add_artificial_nodes(links, nodes, gdobj)
     41 links, nodes = lnu.find_parallel_links(links, nodes)

File ~\miniconda3\Lib\site-packages\rivgraph-0.5.0-py3.11.egg\rivgraph\ln_utils.py:893, in remove_all_spurs(links, nodes, dontremove)
    891 for nid, con in zip(nodes['id'], nodes['conn']):
    892     m = mode(con)
--> 893     if m.count[0] > 1:
    894         # Get link
    895         looplink = m.mode[0]
    896         # Delete link

IndexError: invalid index to scalar variable."

**Comment by jonschwenk** [comment]
Hi @huck-rees , thanks for reporting. We'll need to try to recreate your error to figure out what's happening, but I believe our testing would've caught this awhile ago. Can you provide a printout of the packages w/versions in your environment? 

@jsta Is this something you'd have time to try to dig into?

**Comment by jsta** [comment]
The key thing is that your environment meets the following requirements:

```
- networkx<2.7 # necessary for correct numpy ops
- shapely=1.7.1
- scipy<1.9.0
- numpy<1.23.0
```

**Comment by huck-rees** [comment]
Hello both, I didn't in fact have the correct versions of some of the packages within my environment. It seems to be working fine now, thanks you!
