### ISSUE TITLE
API documentation is blank

### ISSUE THREAD

**Issue by elbeejay** [VeinsOfTheEarth/RivGraph#89]
Need to investigate and fix hosted documentation to show the API Reference information. [Example empty page here](https://veinsoftheearth.github.io/RivGraph/apiref/rivgraph.html).

**Comment by jonschwenk** [comment]
It didn't used to be like this, right?

**Comment by elbeejay** [comment]
Correct, it was definitely working at some point

**Comment by jonschwenk** [comment]
Any idea how to diagnose? Some googling suggests that if all the packages can't be imported, `sphinx-autodoc` could spit out blank pages like we're seeing. There is a warning from the last doc build reminding us that mamba installs may result in unexpected environments...

https://stackoverflow.com/questions/69947560/docstrings-not-populating-sphinx-documentation and https://stackoverflow.com/questions/54965707/sphinx-apidoc-not-automated-enough

**Comment by elbeejay** [comment]
> Any idea how to diagnose?

I don't know, but it's something I can look into when I get a chance to spin up a local environment and fiddle with it. Will check out those links. I think the biggest change was probably when we stopped mocking the dependencies and installed `rivgraph` for the docs build and set up the gallery (https://github.com/VeinsOfTheEarth/RivGraph/commit/3797d7ebe9dce0cf097d45d04046b7a6b45680be), so it could very well be the warning you identified.
