### ISSUE TITLE
Regarding calculation of migration rate of multithreaded rivers.

### ISSUE THREAD

**Issue by rockbusteriitk** [VeinsOfTheEarth/RivGraph#96]
Hi,
I went through the documentation of RivGraph and I am having some difficulty to find clear instructions on how to calculate the migration rates in multi threaded ( especially braided and anabraching) rivers from binary channel masks, using RivGraph.
Could someone please point me to the right resource?

Thank you

**Comment by jonschwenk** [comment]
Hey @rockbusteriitk, RivGraph doesn't provide this functionality. I developed a Matlab program called [RIVMAP](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016EA000196) that can do this, and the [SCREAM program](https://www.sciencedirect.com/science/article/pii/S0034425716302620) by Joel Rowland does a nice job of this, but it's in IDL and you have to contact him to use it. There may be other options out there as well--I haven't stayed on top of the literature.
